---
- name: Create user on all managed nodes
  hosts: multi
  become: true

  tasks:
    - name: Create user ednied
      ansible.builtin.user:
        name: ednied
        shell: /bin/bash
        state: present
...
